baseURL = 'https://organicfoodincubator.netlify.app'
languageCode = 'en-us'
title = 'Organic Food Incubator'

theme = 'organic'


[[menus.main]]
name = 'Who We Are'
pageRef = '/about'
weight = 20

[[menus.main]]
name = 'What We Do'
pageRef = '/services'
weight = 40

[[menus.main]]
name = 'Our Blog'
pageRef = '/blog'
weight = 60

[params]
logo = "images/logo.png"
tagline = "Solutions For Food And Beverage Manufacturing"
subtitle = "We specialize in creating innovative products for CPG brands, food service enterprises, and other innovators the food industry. Whether organic or conventional, offer a complete solution for businesses eager to launch new offerings or expand their existing products in the market. We are a team of chefs, food scientists, and business leaders with a passion for all things food and business."
image = "images/bg.jpg"

  [params.contact_info]
  tel = "(973) 748-0111"
  address = "38 Davey St. Bloomfield, NJ 07003"
  email = "info@organicfoodincubator.com"

  [params.socials]
  facebook_url = "https://www.facebook.com/OrganicFoodIncubator/"
  twitter_url = "https://x.com/OrganicFoodInc"
  instagram_url = "https://instagram.com/OrganicFoodIncubator/"
  youtube_url = "https://www.youtube.com/channel/UCr2dcD-HACpSYL7Bg8DxagA"
