baseURL = 'https://organicfoodincubator.netlify.app'
languageCode = 'en-us'
title = 'Organic Food Incubator'

theme = 'organic'

[[menus.main]]
identifier = 'who-we-are'
name = 'Who We Are'
weight = 20

[[menus.main]]
identifier = 'about'
parent = 'who-we-are'
name = 'About'
pageRef = '/who-we-are/about'
weight = 220

[[menus.main]]
identifier = 'meet-the-team'
parent = 'who-we-are'
name = 'Meet the Team'
pageRef = '/who-we-are/meet-the-team'
weight = 240

[[menus.main]]
identifier = 'building-community'
parent = 'who-we-are'
name = 'Building Community'
pageRef = '/who-we-are/building-community'
weight = 260

[[menus.main]]
identifier = 'friends-of-the-ofi'
parent = 'who-we-are'
name = 'Friends of the OFI'
pageRef = '/who-we-are/friends-of-the-ofi'
weight = 280

[[menus.main]]
identifier = 'services'
name = 'What We Do'
weight = 40

[[menus.main]]
identifier = 'blog'
name = 'Our Blog'
pageRef = '/blog'
weight = 60

[[menus.main]]
identifier = 'contract-manufacturing'
parent = 'services'
name = "Contract Manufacturing"
pageRef = '/services/contract-manufacturing'
weight = 100

[[menus.main]]
identifier = 'operations-management'
parent = 'services'
name = "Outsourcing Solutions"
pageRef = '/services/operations-management'
weight = 110

[[menus.main]]
identifier = 'coaching-and-training'
parent = 'services'
name = "Coaching and Training"
pageRef = '/services/coaching-and-training'
weight = 120

[[menus.main]]
identifier = 'product-development'
parent = 'services'
name = "Product Development"
pageRef = '/services/product-development'
weight = 130

[params]
logo = "images/logo.png"
tagline = "Solutions For Food And Beverage Manufacturing"
subtitle = "We specialize in creating innovative products for CPG brands, food service enterprises, and other innovators the food industry. Whether organic or conventional, offer a complete solution for businesses eager to launch new offerings or expand their existing products in the market. We are a team of chefs, food scientists, and business leaders with a passion for all things food and business."
default_image = "/images/uploads/bg.jpg"

  [params.contact_info]
  tel = "(973) 748-0111"
  address = "38 Davey St. Bloomfield, NJ 07003"
  email = "info@organicfoodincubator.com"

  [params.socials]
  facebook_url = "https://www.facebook.com/OrganicFoodIncubator/"
  twitter_url = "https://x.com/OrganicFoodInc"
  instagram_url = "https://instagram.com/OrganicFoodIncubator/"
  youtube_url = "https://www.youtube.com/channel/UCr2dcD-HACpSYL7Bg8DxagA"
