[build.environment]
HUGO_VERSION = "0.124.0"
TZ = "America/New_York"

[build]
publish = "public"
command = "hugo --gc --minify"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"