backend:
  name: git-gateway
  branch: main

media_folder: "static/images/uploads"

public_folder: "/images/uploads"

collections:
  - name: homepage
    label: Homepage
    folder: content/
    fields:
      - { label: "Body", name: "body", widget: "markdown" }
  - name: blog
    label: Blog
    folder: "content/blog"
    create: true
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - label: Parameters
        name: "params"
        widget: object
        fields:
          - { label: "Hero Image", name: "image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Date", name: "date", widget: "datetime" }
  - name: services
    label: Services
    folder: content/services
    fields:
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "services",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
