baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Blog'
pageRef = '/blog'
weight = 20

[params]
  logo = "images/logo.png"
  tagline = "Your Text Here"

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
